name: test_gpu
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -e "```nvidia-smi```\\ntest" > report.md
          
          cml-send-comment report.md
